# Generated by Django 4.2.2 on 2023-06-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/board')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conferenceroom')),
            ],
        ),
    ]
