# Generated by Django 4.2.2 on 2023-06-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
    ]
